### ISSUE TITLE
Wallpaper of devicons screenshot

### ISSUE THREAD

**Issue by PythonPizzaDE** [NvChad/nvchad.github.io#117]
Hello,
I don't know if this is the right place to ask something like this can you publish the link to the wallpaper used on [this](https://github.com/NvChad/nvchad.github.io/blob/src/static/img/features/devicons.png) screenshot?
Have a Great Day!

**Comment by siduck** [comment]
[@PythonPizzaDE ](https://raw.githubusercontent.com/siduck/dotfiles/master/wall/neon.png)
