### ISSUE TITLE
Pre-requisites does not mention build-essentials

### ISSUE THREAD

**Issue by bradtaniguchi** [NvChad/nvchad.github.io#122]
Hello, 

I was following the installation instructions for `nvchad` on a relatively new (ubuntu) WSL2 instance, to "spice up" my rather weak base nvim configuration, and was following:
https://nvchad.com/quickstart/install#pre-requisites

However, after running:
```bash
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```

I was presented with an error within nvim (didn't grab a screenshot)

mentioning **no C compiler found**. 

This is a miss on my part as I forgot to ever install `build-essentials` on my machine. However I think adding it as a pre-req in the docs could help onboard those who either don't know they even need this package, or see this error, or at least need a reminder they need this as a pre-req.

**Comment by siduck** [comment]
you are right @bradtaniguchi , will add it from v2.0
