### ISSUE TITLE
FYI nvchad.com 404's

### ISSUE THREAD

**Issue by mhamrah** [NvChad/nvchad.github.io#127]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/91162/224517471-301c3bc7-c571-4140-8fcc-f2afe55628c8.png">

**Comment by mikaizhu** [comment]
the same

**Comment by siduck** [comment]
nvchad.github.io should work

**Comment by siduck** [comment]
idk why our custom domain keeps getting removed after every push, lemme check!

**Comment by siduck** [comment]
fixed
