### ISSUE TITLE
Table of content don’t work on iPad

### ISSUE THREAD

**Issue by ryannewcomer** [NvChad/nvchad.github.io#130]
https://user-images.githubusercontent.com/88273136/224721864-e41c2403-361a-4267-ab18-70e2782c6d25.MOV
As you can see, when I click the button to show the page content, it just go to the main page. But this is’t the problem on pc.

**Comment by siduck** [comment]
hi @ryannewcomer does it work with chrome/firefox? im assuming we get this issue with safari

**Comment by ryannewcomer** [comment]
Yes, it is on safari, also, the page content work on the features pages
![4847D046-DF15-4A9B-A0C7-444DBC38F471](https://user-images.githubusercontent.com/88273136/224730199-42ddc915-22be-4a62-bcdb-477f224fd19e.png)

**Comment by ryannewcomer** [comment]
But it is a bit weird, when I click a button (e.g. cheat sheet) the content page don’t go.

https://user-images.githubusercontent.com/88273136/224732204-ca1a06fe-17a9-4042-8d52-f1cd82bd7562.MOV

**Comment by siduck** [comment]
@ryannewcomer still facing this issue

**Comment by ryannewcomer** [comment]
Yes

**Comment by siduck** [comment]
> Yes

even if i fixed this issue, i wont be able to test asap man, table of contents are just links.. idk why clicking those will get you to home page, does this happen on other browsers?

**Comment by siduck** [comment]
ig this should be resolved by now :thinking:
