### ISSUE TITLE
website is down/404

### ISSUE THREAD

**Issue by abhaytaras7** [NvChad/nvchad.github.io#135]
**Description**
Website is not be found .

**Reproduced issue**
 
![image](https://user-images.githubusercontent.com/73850631/226083854-180575a1-4b40-48b7-9adc-b4b0a8c51f65.png)
![image](https://user-images.githubusercontent.com/73850631/226083995-f046a670-09d6-4d55-a372-ee1c62eaa1da.png)

**Expected behavior**
A working website .

**Desktop (please complete the following information):**
 - Operating System : linux/debain
 - Terminal : xfce

**Comment by siduck** [comment]
@abhaytaras7 can you check it now?

**Comment by abhaytaras7** [comment]
Website is back online 
![image](https://user-images.githubusercontent.com/73850631/226086614-7a53f690-505e-4842-854f-f00d9662303a.png)

**Comment by siduck** [comment]
but our readme images look broken!

**Comment by siduck** [comment]
nvm it works now. deployed to gh-pages again 
![image](https://user-images.githubusercontent.com/59060246/226093254-e19e0760-f6f4-4bda-a688-a2d424ea3b47.png)

cuz netlify might cost us in the future
