### ISSUE TITLE
Is multi-languages gonna be supported?

### ISSUE THREAD

**Issue by Dianshii** [NvChad/nvchad.github.io#136]
I'm thinking of translating the docs into Chinese and have done the "quick start" section. I'm happy to translate the docs if you plan to add language selection to the site.

**Comment by siduck** [comment]
hi @Dianshii wouldnt that make the config hard for non en users? like the config's in english then i suppose those users would also be able to understand english beforehand

**Comment by Dianshii** [comment]
@siduck Cus I feel like the nvchad doc is a really good starting point. With a quick lesson of lua. You made it short and easy to understand and I like it. But you know for non-native speakers it's always much easier if there's some basic lessons that can start in there own language, even if they've learned English.
Different people have different level of English comprehension.
And I think it'll be good if there's some more step-by-step template of adding and configuring plugins and autocmds, so that you can start playing around without sitting for hours wondering why this plugin doesn't work.

**Comment by siduck** [comment]
oh I get it now, but @Dianshii i do not know how to add support for other languages tho!

**Comment by siduck** [comment]
our site isnt using docusuarus or other site builders like before btw

**Comment by Dianshii** [comment]
@siduck Ok...I guess I just give it up then. Notice me anytime if you're gonna add different language docs, I still feel NvChad if my favorite Neovim config.
