### ISSUE TITLE
Bad config file path in LSP config section

### ISSUE THREAD

**Issue by Tenshock** [NvChad/nvchad.github.io#149]
In [Setup lsp server](https://nvchad.com/docs/config/lsp), instructions to setup lsp configuration mismatch between the configuration override in `custom/plugins.lua` and the example provieded with path `custom/plugins/lspconfig.lua`.

The plugin override in `custom/plugins.lua` specifies a require to [`custom.plugins.lspconfig`](https://github.com/NvChad/nvchad.github.io/blob/src/src/routes/(index)/docs/config/lsp.mdx?plain=1#L15) and the example provided has [`custom/configs/lspconfig.lua`](https://github.com/NvChad/nvchad.github.io/blob/src/src/routes/(index)/docs/config/lsp.mdx?plain=1#L22) as target file.

Either update the require to match as follows
```markdown
{- require "custom.plugins.lspconfig" -}
{+ require "custom.configs.lspconfig" +}
```

or update the target file to `custom/plugins/lspconfig.lua`

P.S: the doc is well made, thanks for the project!

**Comment by siduck** [comment]
hi @Tenshock , feel free to send a PR :D

**Comment by siduck** [comment]
thanks for reporting @Tenshock
