### ISSUE TITLE
cant find install intructions

### ISSUE THREAD

**Issue by matthiasdebernardini** [NvChad/nvchad.github.io#155]
how to isntall?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/233789295-a3332226-b783-408c-91cd-3b2c84355eef.png)
https://nvchad.com/docs/quickstart/install

**Comment by matthiasdebernardini** [comment]
none of the pages were loading, several pages don't load properly - website looks super complicated for something delivering text

**Comment by siduck** [comment]
@matthiasdebernardini does nvchad.netlify.app work?

**Comment by siduck** [comment]
I think its related to https://github.com/NvChad/nvchad.github.io/issues/147

**Comment by matthiasdebernardini** [comment]
Yes it did.
