### ISSUE TITLE
Main Table of Content doesn't show on mobile devices

### ISSUE THREAD

**Issue by kachidk** [NvChad/nvchad.github.io#156]
The page content shows but not the Table of Content

![image](https://user-images.githubusercontent.com/61981167/235287634-2766a7be-cb7c-400d-85f9-48ba5ea229ff.png)

**Comment by siduck** [comment]
will fix tomorrow!

**Comment by Z3rio** [comment]
@siduck I believe you can close this as completed, seems to be resolved.

**Comment by siduck** [comment]
@Z3rio could you show how  it looks now?

**Comment by kachidk** [comment]
The issue is still there. There is not way to navigate the sub menu of the docs.

![Screenshot_20230614-073303.png](https://github.com/NvChad/nvchad.github.io/assets/61981167/e7c69786-f9e4-487d-8e7c-d916ca44c462)

**Comment by Z3rio** [comment]
Hm odd, I tried using dev tools to resize and it worked fine.
Is it perhaps something which ONLY happens on real mobile devices?

If it's not fixed yet I would love to take a shot at fixing it

**Comment by siduck** [comment]
> The issue is still there. There is no way to navigate the sub menu of the docs.
> 
> ![Screenshot_20230614-073303.png](https://user-images.githubusercontent.com/61981167/245696971-e7c69786-f9e4-487d-8e7c-d916ca44c462.png)

no, you opened issue for table of contents only, not the navbar. Open another issue for it as table of contents show now
