### ISSUE TITLE
Improve UX in grid view of themes page

### ISSUE THREAD

**Issue by rish106** [NvChad/nvchad.github.io#160]
When you scroll down and click on a theme to look at its preview, then you're directed back to top of the gallery after closing the preview. It would be better if the scroll position is restored.
![my](https://github.com/NvChad/nvchad.github.io/assets/36294070/b3626aba-0205-49b9-8063-cbaad0cca1ca)

**Comment by siduck** [comment]
@rish106 you're right, will fix this today
