### ISSUE TITLE
Should recommendation for null-ls be switched

### ISSUE THREAD

**Issue by ElmeriVincent** [NvChad/nvchad.github.io#166]
Since null-ls will be archived on **August 11, 2023**,  should the recommendation like the one seen in https://nvchad.com/docs/config/format_lint be switched to an alternative with new examples or at least to be added along with null-ls?

**Comment by siduck** [comment]
@ElmeriVincent not yet! read folke's comment here https://www.reddit.com/r/neovim/comments/14z79qm/what_is_the_solution_for_nullls_being_archived/
