### ISSUE TITLE
Navbar unresponsive

### ISSUE THREAD

**Issue by atb85** [NvChad/nvchad.github.io#176]
As seen in the picture, the navbar appears not to scale down with the content on some mobile devices

(apple iPhone 12 mini) 

this leaves the collapse button outside the normal viewport unless scrolled to

![IMG_3569](https://github.com/NvChad/nvchad.github.io/assets/62593439/f5e9382f-5d5b-4162-b42d-80719f24ec01)

**Comment by siduck** [comment]
show image
