### ISSUE TITLE
add docs for non-interactive bootstrapping

### ISSUE THREAD

**Issue by CrispyBaccoon** [NvChad/nvchad.github.io#190]
non-interactive bootstrapping was added in [#(NvChad/NvChad)2528](https://github.com/NvChad/NvChad/pull/2528).

yet there are no docs explaining this process.

**Comment by CrispyBaccoon** [comment]
docs for this could be something like:
```markdown
    NvChad can be installed non-interactively using:
    ```shell - linux
    git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 &&\
    NVCHAD_INSTALL_EXAMPLE_CONFIG=no nvim -c "autocmd User PackerComplete quitall" -c "quitall"
    ```
    ```shell - windows
    $NVCHAD_INSTALL_EXAMPLE_CONFIG=no; git clone https://github.com/NvChad/NvChad $HOME\AppData\Local\nvim --depth 1 && nvim
    ```
    ```shell - docker
    docker run -w /root -it --rm alpine:latest sh -uelic '
    apk add git nodejs neovim ripgrep build-base wget --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim
    NVCHAD_INSTALL_EXAMPLE_CONFIG=no nvim -c "autocmd User PackerComplete quitall" -c "quitall"
    '
    ```
```

since this feature would mainly be used in docker images documentation for this platform is highly important.

**Comment by siduck** [comment]
> PackerComplete 
we use lazy.nvim,   so ig its lazydone

**Comment by x0wllaar** [comment]
My original intent for the command in [#2528 ](https://github.com/NvChad/NvChad/pull/2528) was to force early install of as many packages as possible so that they get baked into the Docker image (for e.g. completely reproducible devenvs). 

If there's a better way to do it, it should be put into the docs instead.

**Comment by siduck** [comment]
@CrispyBaccoon why's packercomplete required here?

**Comment by siduck** [comment]
![image](https://github.com/NvChad/nvchad.github.io/assets/59060246/5493640c-28ff-4b85-ab33-9ac9860565f2)

--headless works fine :D
