### ISSUE TITLE
Installation/Uninstall Commands Not Formatted Correctly

### ISSUE THREAD

**Issue by Kaszanas** [NvChad/nvchad.github.io#194]
It seems that the commands are formatted incorrectly:

![image](https://github.com/NvChad/nvchad.github.io/assets/34846245/441e7a02-2faa-4e3f-a424-6eab49baa8c8)

These are not valid shell commands.

**Comment by siduck** [comment]
https://github.com/NvChad/nvchad.github.io/pull/193 
@neilfranci

**Comment by neilfranci** [comment]
One thing that I hate most about Windows. Why can't they just make Powershell V7 the default?

The command for Powershell work! If you have Powershell V7 installed @@
I suggest you install Powershell V7 because it's the most used and the features it has.
or you can do the old thing:
```pwsh
(git clone https://github.com/NvChad/NvChad $ENV:USERPROFILE\AppData\Local\nvim --depth 1) -AND (nvim)
```
I mean you need to wrap it and use `-AND` lol. Because old Powershell doesn't have `&&` syntax 😕

**Comment by siduck** [comment]
ah idk any of  this lol, all pcs in my home use linux :relaxed:

**Comment by Kaszanas** [comment]
> One thing that I hate most about Windows. Why can't they just make Powershell V7 the default?
> 
> The command for Powershell work! If you have Powershell V7 installed @@
> I suggest you install Powershell V7 because it's the most used and the features it has.
> or you can do the old thing:
> ```pwsh
> (git clone https://github.com/NvChad/NvChad $ENV:USERPROFILE\AppData\Local\nvim --depth 1) -AND (nvim)
> ```
> I mean you need to wrap it and use `-AND` lol. Because old Powershell doesn't have `&&` syntax 😕

The copy button for code that's there also copies the markdown heading (notice the black background)

And technically these commands can be run consecutively without wrapping I think.

**Comment by neilfranci** [comment]
> The copy button for code that's there also copies the markdown heading (notice the black background)
> 
> And technically these commands can be run consecutively without wrapping I think.

1. Which copy button are we talking about? Is the one in the nvchad website or the GitHub? Because I don't see any button on the nvchad website. 😵‍💫
2. Which Powershell version are you using? Because I can only run this in Powershell V5 (the old one) with wrapping, I'm not sure how you  run this consecutively:
`(git clone https://github.com/NvChad/NvChad $ENV:USERPROFILE\AppData\Local\nvim --depth 1) -AND (nvim)` without wrapping?
- This drives me nuts, we need more info about this.

**Comment by Kaszanas** [comment]
Found another one...

See the copy button that you can click on the right?

![image](https://github.com/NvChad/nvchad.github.io/assets/34846245/02637338-3e15-47f4-9f54-084ed35fef73)

Yeah it copies everything in scope of the black background.

So now if I do the following:

1. Switch to another installation tab (copy code buttons vanish - they were there yesterday)
![image](https://github.com/NvChad/nvchad.github.io/assets/34846245/68d26edb-1c67-4605-b476-7de975759a8d)
2. Switch back to the Linux installation tab (copy code button no longer shows, it was there in the first screenshot)
![image](https://github.com/NvChad/nvchad.github.io/assets/34846245/dfc233a5-852c-4994-aff5-eb04e488e047)

Browser I use is Chrome.

## Back to the issue at hand:

This part of text looks like it is meant to be a markdown heading
`# if you're using Command Prompt(CMD)`
# if you're using Command Prompt(CMD) 

And when the button for copying code was showing clicking it would cause the entirety of the content in the scope of the black background to be copied including this markdown heading and a newline. Similarly to other pieces of code showcased in the documentation.

![image](https://github.com/NvChad/nvchad.github.io/assets/34846245/a80d0ec6-4bbb-4b13-b750-cc7c090e8f27)

You have a button for copying the code but you have different OS's included so the button becomes just a nice (not very useful) decoration.

**Comment by neilfranci** [comment]
@siduck Hmm, out of my scope. 
Never thought someone would click that because it's just a plain markdown so users can just select the path they one and done. And I don't see a scenario where the user could go to the Windows install section and then go back to Linux/Mac...

**Comment by Kaszanas** [comment]
> @siduck Hmm, out of my scope. Never thought someone would click that because it's just a plain markdown so users can just select the path they want and done. And I don't see a scenario where the user could go to the Windows install section and then go back to Linux/Mac...

That is one issue, but another one is mixing markdown, newlines, and code that is supposed to be copied together as follows:

![image](https://github.com/NvChad/nvchad.github.io/assets/34846245/325150d5-db7e-4a30-8ce6-e8836c871a41)

This makes the copy button unusable because this would copy more than just the command that the user is supposed to run in the terminal but instead it would copy all of the junk that you don't want.

**Comment by siduck** [comment]
ok looks like a bug in the website's code which deals with copy, will fix soon
