### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by autolisis** [NvChad/nvchad.github.io#197]
The index page is returning a blank page.

<img width="1709" alt="image" src="https://github.com/NvChad/nvchad.github.io/assets/25099244/7a8d2327-d01c-43b4-98f7-4cf88db3163f">

Specific subpages load but still return a 404

<img width="1713" alt="image" src="https://github.com/NvChad/nvchad.github.io/assets/25099244/f3c28f6b-8a1e-482c-a4ce-5d91a94d9652">

**Comment by siduck** [comment]
looking into it
