### ISSUE TITLE
Typo in the Installation docs?

### ISSUE THREAD

**Issue by cqhudson** [NvChad/nvchad.github.io#201]
I believe there is a typo in the docs when explaining the installation process for NvChad on Windows (at this link, I clicked the windows button to display the installation process: https://nvchad.com/docs/quickstart/install/). 

Specifically, this portion of the file located at `/src/components/docpage/install.tsx` lines 30-33:

```
<li>For CMD : %LOCALAPPDATA%\nvim </li>
<pre class="hljs">C:\Users\%USERNAME%\AppData\Local\nvim</pre>
<li>For CMD : %LOCALAPPDATA%\nvim </li>
<pre class="hljs">C:\Users\$ENV:USERNAME\AppData\Local\nvim</pre>
```
I believe the second `<li>` and `<pre>` are supposed to describe PowerShell usage rather than CMD (based on the path given in the second `<pre>` tag which is using PowerShell syntax for a filepath `C:\Users\$ENV:USERNAME\AppData\Local\nvim`).

A fix for this might be to change the second `<li>` tag (line 32) to: `<li>For PowerShell : $ENV:LocalAppData\nvim </li>`

If this is actually an issue, and not a misunderstanding on my part, I could write a pull-req for this if acceptable.

**Comment by siduck** [comment]
thanks for correcting, fixed in latest commit.
