### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by hexWars** [NvChad/nvchad.github.io#202]
I would like to know how this [image](https://camo.githubusercontent.com/e25ff2dc583aa8ee13c25f8ed3dbc73464621a260c8f1af3f7d485493de678cc/68747470733a2f2f6e76636861642e636f6d2f6e6577732f76322e302e77656270) was generated, I hope it won't bother you.

**Comment by siduck** [comment]
i    created a rectangle in figma and added some gradient bg to it, then nvchad logo and some nvchad screenshots

**Comment by hexWars** [comment]
Thanks
