### ISSUE TITLE
404 pages in docs search results

### ISSUE THREAD

**Issue by sharu725** [NvChad/nvchad.github.io#219]
Upon searching for something in the docs and clicking on the search result we see 404
![image](https://github.com/user-attachments/assets/abc361ac-3175-4e4b-9460-c3827621de2d)

Maybe algolia has stale data

Example link the returns 404 - https://nvchad.com/docs/config/format_lint#linting

![image](https://github.com/user-attachments/assets/48b18c09-7868-47a0-b96b-8f3e4be00e83)

**Comment by siduck** [comment]
crawled the website again, no more dead links!
