### ISSUE TITLE
Doesn't respect XDG base directory specification 

### ISSUE THREAD

**Issue by monke0192** [NvChad/nvchad.github.io#23]
In the installation guide, the guide uses `~/.config` and `~/.local/share` instead of `${XDG_CONFIG_HOME}` and `${XDG_DATA_HOME}`. [Link to XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by siduck76** [comment]
> In the installation guide, the guide uses `~/.config` and `~/.local/share` instead of `${XDG_CONFIG_HOME}` and `${XDG_DATA_HOME}`. [Link to XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

what if those variables arent set? would it default to ~/.config and ~/.local/share?

**Comment by siduck76** [comment]
i havent set those variables , it defaults to just the home folder :/ .
![image](https://user-images.githubusercontent.com/59060246/135421258-bdf26258-3917-4280-b838-54db7a4c657a.png)

**Comment by monke0192** [comment]
If those variables aren't set, use `${foo:-bar}`. (`${XDG_CONFIG_HOME:-~/.config}`)

**Comment by G-Rowell** [comment]
@monke0192 

I am a supporter of $XDG specification,

is there anywhere besides the install docs that hard-code this directory?

I would guess not as we use `vim.stdpath "confg"` instead of a fully hard-coded path.

**Comment by G-Rowell** [comment]
However, I would be hesitant to add this to our install script like below: 

 `git clone NVCHAD ${XDG_CONFIG_HOME:-~/.config}`

As any user who uses a non-standard $XDG dir setup, can easily change this, and I think it should work well?

**Comment by monke0192** [comment]
> @monke0192
> 
> I am a supporter of $XDG specification,
> 
> is there anywhere besides the install docs that hard-code this directory?
> 
> I would guess not as we use `vim.stdpath "confg"` instead of a fully hard-coded path.

https://nvchad.github.io/config#default-config
![image](https://user-images.githubusercontent.com/50064042/135426630-f4bcb855-77bd-46f6-b007-3d1d4fb7c965.png)

**Comment by monke0192** [comment]
> However, I would be hesitant to add this to our install script like below:
> 
> `git clone NVCHAD ${XDG_CONFIG_HOME:-~/.config}`
> 
> As any user who uses a non-standard $XDG dir setup, can easily change this, and I think it should work well?

It works well
