### ISSUE TITLE
error about `pluginConfs` and `pluginConfigs`

### ISSUE THREAD

**Issue by yzld2002** [NvChad/nvchad.github.io#48]
https://github.com/NvChad/nvchad.github.io/blob/b4491a61bd513c2a4089220c6bb6f3d98992c6a3/docs/config/Custom%20config.md?plain=1#L77-L86

seems the variable name does not match between the definition (`pluginConfs `) and usage (`pluginConfigs `)
which casues the custom config does not get loaded and nvim does not throw an error about it, at least in `checkhealth`

Also a noob question, I don't see that NvChad complain about this custom config error, just load the default config instead, am I right?

**Comment by siduck** [comment]
thanks for reporting this
