### ISSUE TITLE
Add snippets and debugger plugins to extras

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [NvChad/nvchad.github.io#49]
I wanted to install some snippets like honza/vim-snippets but written in lua. And a debugger that works for multiple languages. I haven't seen them recommended in the extras on the documentation.

**Comment by siduck** [comment]
@HarleyQuinn-Z6 we already have friendly snippets , they're disabled by default tho. As for the debugger, I dont use DAP or such stuff. PR for it if you can.

**Comment by HarleyQuinn-Z6** [comment]
I haven't used anyone yet but I was hoping I could use neovim as a normal IDE by using NvChad. If I learn of a debugger plugin and remember about this issue I'll make sure to add it to the extras and make a PR.
