### ISSUE TITLE
wrong word in chapter "Learning Lua"

### ISSUE THREAD

**Issue by crafter695565** [NvChad/nvchad.github.io#72]
![image](https://user-images.githubusercontent.com/62090995/172030817-60750a7d-10e3-4f1c-a8bd-24d78555c22d.png)
As you can see,it's a wrong word.
I'm too lazy to submit a PR.

**Comment by siduck** [comment]
add a PR lul

**Comment by crafter695565** [comment]
> add a PR lul

fine （；´д｀）ゞ
