### ISSUE TITLE
contradiction on options page

### ISSUE THREAD

**Issue by justin-f-perez** [NvChad/nvchad.github.io#84]
On [Options page](https://nvchad.github.io/config/options) note at top says "these" go in chadrc...

> (Note: You should add these in chadrc )

... but 3 out of 4 of "these" subsections says use `custom/init.lua`. 

> ## Options
> (Note: You should add these in chadrc )
> 
> ### Override default options
> * Put them in `custom/init.lua`
> * New options can put in the same file too
>
> ### Autocmds & Globals
> * Load these in `custom/init.lua `file
>
> ### Lazy loading
> * We lazy load almost 95% of the plugins, so we expect you to lazy load the plugins you've added to reduce startuptime. We don't want users making NvChad slow just because they didn't lazy load plugins they've added!
>
> * Check [packer's readme](https://github.com/wbthomason/packer.nvim#specifying-plugins) for more info!
>
> ### Snippets
> * Put this in your `custom/init.lua`
> ```lua
> vim.g.luasnippets_path = "your snippets path"
> ```

**Comment by siduck** [comment]
thanks for reporting!

removed it in recent commit https://github.com/NvChad/nvchad.github.io/commit/092d36def3711890aa5364b4ee4d6c2454f8736e
