### ISSUE TITLE
User plugins syntax

### ISSUE THREAD

**Issue by amittamari** [NvChad/nvchad.github.io#87]
https://github.com/NvChad/nvchad.github.io/blob/0973bb7b5c5b6675db67ededd82c69db67512d68/docs/config/plugins.md?plain=1#L31-L35

Does not actually work, instead I have to do to this:
```lua
M.plugins = {
    user = {
        ["Pocco81/TrueZen.nvim"] = {},
    }
}
```

Then run :PackerInstall. Is this intentional or am I missing smth?

**Comment by siduck** [comment]
old plugin syntax is depreceated, check the new one

**Comment by siduck** [comment]
```lua

M.plugins = {

[ 'pocoo.....'] = {}

}
```

**Comment by siduck** [comment]
updated the docs & corrected them

**Comment by amittamari** [comment]
looks like this:
https://github.com/NvChad/nvchad.github.io/blob/e381a2ce20f84582624d849cf7add4bbb8fc6679/docs/config/plugins.md?plain=1#L36

should be:
`custom/plugins.lua`

**Comment by siduck** [comment]
@amittamari both will be the same when calling 

```lua
requre "custom.plugins"
```

**Comment by siduck** [comment]
same with the default plugins module 

we could just save it in `lua/plugins.lua`

but we save it in `plugins/init.lua` because the plugins dir will be then used for storing plugin configs. 

same with `custom/plugins` folder, both will work but I like to keep it organized
